server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:file:C:/Users/prkimoth/test/testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    platform: h2
    initialize: true
    schema: classpath:schema.sql

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
h2:
  console:
    enable: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE


